TwigaCRM/Pages/PerformanceReports/MonthlyPerformanceReports.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TwigaCRM.Data;
using TwigaCRM.Models;
using TwigaCRM.Services;

namespace TwigaCRM.Pages.PerformanceReports
{
    [Authorize]
    public class MonthlyPerformanceReportModel : PageModel
    {
        private readonly TwigaCRM.Data.ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly INotyfService _toastNotification;
        private readonly CheckPermissionsService _checkPermissions;

        public MonthlyPerformanceReportModel(TwigaCRM.Data.ApplicationDbContext context, UserManager<AppUser> userManager, INotyfService toastNotification, CheckPermissionsService checkPermissions)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
            _checkPermissions = checkPermissions;
        }
        public int Week { get; set; }

        public List<DailyMovementReport> DailyMovementReports { get; set; }
        public IList<SalesMovement> SalesMovements { get; set; }


        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            [Display(Name = "SalesPerson")]
            public string SalesPersonId { get; set; }

            [Required]
            [Display(Name = "Month")]
            public int Month { get; set; }

            [Required]
            [Display(Name = "FinancialYear")]
            public int FinancialYearId { get; set; }

        }
        [BindProperty]
        public DailyMovementReport DailyMovementReport { get; set; }
        public List<Target> Targets { get; set; }
        public List<DailyMovement> DailyMovements { get; set; }
        public List<ReportModel> Reports { get; set; }
        public class ReportModel
        {
            [Required]
            [Display(Name = "Product")]
            public int ProductId { get; set; }
            public Product Product { get; set; }

            [Required]
            [Display(Name = "ActualMovement")]
            public decimal ActualMovement { get; set; }

            [Required]
            [Display(Name = "TargetMovement")]
            public decimal TargetMovement { get; set; }

        }
        public List<MonthlyMovement> Movements { get; set; }
        public class MonthlyMovement
        {
            public int ProductId { get; set; }
            public Product Product { get; set; }

            public decimal MonthMovement { get; set; }
        }

        public bool IsPermitted { get; private set; }
        public async Task<IActionResult> OnGetAsync(int FinancialYearId, int Month, string SalesPersonId)
        {
            IsPermitted = _checkPermissions.CheckPermission(User, "generate_performance_reports");
            if (!IsPermitted)
            {
                return RedirectToPage("/403");
            }
            ViewData["shownav"] = _checkPermissions.NavPermissionAsync(User);
            ViewData["FinancialYears"] = _context.FinancialYear.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.StartDate.Year + " - " + a.EndDate.Year
                                            }).ToList();
            ViewData["SalesPersons"] = _userManager.Users.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.FirstName + " " + a.LastName
                                            }).ToList();
            FinancialYear financialYear = await _context.FinancialYear.FirstOrDefaultAsync(f => f.Id == FinancialYearId);
            DailyMovementReports = await _context.DailyMovementReport
                .Include(d => d.SalesPerson)
                .Include(d => d.DailyMovements)
                .Where(d => d.SalesPersonId == SalesPersonId && d.SalesDate.Month == Month && d.TLstatus == "Approved").OrderByDescending(s => s.Id).ToListAsync();

            DailyMovements = await _context.DailyMovement
                    .Include(d => d.Product)
                    .Include(d => d.DailyMovementReport)
                    .Include(d => d.DailyMovementReport.SalesPerson)
                    .Where(d => d.DailyMovementReport.SalesPersonId == SalesPersonId && d.DailyMovementReport.SalesDate.Month == Month && (d.DailyMovementReport.SalesDate.Date >= financialYear.StartDate.Date && d.DailyMovementReport.SalesDate.Date <= financialYear.EndDate.Date) && d.DailyMovementReport.TLstatus == "Approved").OrderByDescending(s => s.Id).ToListAsync();
            SalesMovements = await _context.SalesMovement
                .Include(s => s.FinancialYear)
                .Include(s => s.SalesPerson)
                .Include(s => s.Targets)
                .Where(s => s.TLstatus == "Approved").OrderByDescending(s => s.Id).ToListAsync();

            Targets = await _context.Target
                    .Include(t => t.Product)
                    .Include(t => t.SalesMovement)
                    .Include(t => t.SalesMovement.SalesPerson)
                    .Where(d => d.SalesMovement.SalesPersonId == SalesPersonId && d.SalesMovement.Month == Month && d.SalesMovement.FinancialYearId == financialYear.Id && d.SalesMovement.TLstatus == "Approved").OrderByDescending(s => s.Id).ToListAsync();
            _toastNotification.Success("Report Ready!");
            return Page();
        }
    }
}

TwigaCRM/Pages/PerformanceReports/PerformanceReports.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Xml.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using NuGet.Packaging;
using TwigaCRM.Data;
using TwigaCRM.Models;
using TwigaCRM.Services;

namespace TwigaCRM.Pages.PerformanceReports
{
    [Authorize]
    public class PerformanceReportsModel : PageModel
    {
        private readonly TwigaCRM.Data.ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly INotyfService _toastNotification;
        private readonly CheckPermissionsService _checkPermissions;

        public PerformanceReportsModel(TwigaCRM.Data.ApplicationDbContext context, UserManager<AppUser> userManager, INotyfService toastNotification, CheckPermissionsService checkPermissions)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
            _checkPermissions = checkPermissions;
        }

        public List<DailyMovementReport> DailyMovementReports { get; set; }
        public IList<SalesMovement> SalesMovements { get; set; }


        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            [Display(Name = "SalesPerson")]
            public string SalesPersonId { get; set; }

            [Required]
            [Display(Name = "Month")]
            public int Month { get; set; }

            [Required]
            [Display(Name = "FinancialYear")]
            public int FinancialYearId { get; set; }

        }
        public bool IsPermitted { get; private set; }
        public async Task<IActionResult> OnGetAsync()
        {

            IsPermitted = _checkPermissions.CheckPermission(User, "generate_performance_reports");
            if (!IsPermitted)
            {
                return RedirectToPage("/403");
            }
            ViewData["shownav"] = _checkPermissions.NavPermissionAsync(User);

            DailyMovementReports = await _context.DailyMovementReport
                .Include(d => d.SalesPerson).ToListAsync();

            SalesMovements = await _context.SalesMovement
                .Include(s => s.FinancialYear)
                .Include(s => s.SalesPerson).ToListAsync();
            ViewData["FinancialYears"] = _context.FinancialYear.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.StartDate.Year + " - " + a.EndDate.Year
                                            }).ToList();
            ViewData["SalesPersons"] = _userManager.Users.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.FirstName + " " + a.LastName
                                            }).ToList();

            return Page();
        }
        public List<Target> Targets { get; set; }
        public List<DailyMovement> DailyMovements { get; set; }
        public List<ReportModel> Reports { get; set; }
        public class ReportModel
        {
            [Required]
            [Display(Name = "Product")]
            public int ProductId { get; set; }
            public Product Product { get; set; }

            [Required]
            [Display(Name = "ActualMovement")]
            public decimal ActualMovement { get; set; }

            [Required]
            [Display(Name = "TargetMovement")]
            public decimal TargetMovement { get; set; }

        }
        public List<MonthlyMovement> Movements { get; set; }
        public class MonthlyMovement
        {
            public int ProductId { get; set; }
            public Product Product { get; set; }

            public decimal MonthMovement { get; set; }
        }
        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            IsPermitted = _checkPermissions.CheckPermission(User, "generate_performance_reports");
            if (!IsPermitted)
            {
                return RedirectToPage("/403");
            }
            ViewData["shownav"] = _checkPermissions.NavPermissionAsync(User);
            FinancialYear theFinancialYear = await _context.FinancialYear.FirstOrDefaultAsync(f => f.Id == Input.FinancialYearId);
            if (!ModelState.IsValid)
            {
                _toastNotification.Error("Invalid Inputs!");
                return RedirectToPage("./PerformanceReports");
            }


            return RedirectToPage("./MonthlyPerformanceReports", new { FinancialYearId = Input.FinancialYearId, Month = Input.Month, SalesPersonId = Input.SalesPersonId });
        }
        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostWeeklyPerformanceAsync()
        {
            IsPermitted = _checkPermissions.CheckPermission(User, "generate_performance_reports");
            if (!IsPermitted)
            {
                return RedirectToPage("/403");
            }
            ViewData["shownav"] = _checkPermissions.NavPermissionAsync(User);
            FinancialYear theFinancialYear = await _context.FinancialYear.FirstOrDefaultAsync(f => f.Id == Input.FinancialYearId);
            if (!ModelState.IsValid)
            {
                _toastNotification.Error("Invalid Inputs!");
                return RedirectToPage("./PerformanceReports");
            }


            return RedirectToPage("./WeeklyPerformanceReports", new { FinancialYearId = Input.FinancialYearId, Month = Input.Month, SalesPersonId = Input.SalesPersonId });
        }
    }
}

TwigaCRM/Pages/PerformanceReports/RAMCollectionMonthlyPerformanceReports.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TwigaCRM.Data;
using TwigaCRM.Models;
using TwigaCRM.Services;

namespace TwigaCRM.Pages.PerformanceReports
{
    [Authorize]
    public class RAMCollectionMonthlyPerformanceReportModel : PageModel
    {
        private readonly TwigaCRM.Data.ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly INotyfService _toastNotification;
        private readonly CheckPermissionsService _checkPermissions;

        public RAMCollectionMonthlyPerformanceReportModel(TwigaCRM.Data.ApplicationDbContext context, UserManager<AppUser> userManager, INotyfService toastNotification, CheckPermissionsService checkPermissions)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
            _checkPermissions = checkPermissions;
        }
        public int Week { get; set; }

        public List<RAMDailyCollectionReport> RAMDailyCollectionReports { get; set; }
        public IList<RAMCollectionTarget> RAMCollectionTargets { get; set; }


        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            [Display(Name = "RAM")]
            public string RAMId { get; set; }

            [Required]
            [Display(Name = "Month")]
            public int Month { get; set; }

            [Required]
            [Display(Name = "FinancialYear")]
            public int FinancialYearId { get; set; }

        }
        [BindProperty]
        public RAMDailyCollectionReport RAMDailyCollectionReport { get; set; }
        public List<RAMCollectionTargetMapping> RAMCollectionTargetMappings { get; set; }
        public List<RAMDailyCollection> RAMDailyCollections { get; set; }

        public bool IsPermitted { get; private set; }
        public async Task<IActionResult> OnGetAsync(int FinancialYearId, int Month, string RAMId)
        {
            IsPermitted = _checkPermissions.CheckPermission(User, "generate_RAM_performance_reports");
            if (!IsPermitted)
            {
                return RedirectToPage("/403");
            }
            ViewData["shownav"] = _checkPermissions.NavPermissionAsync(User);
            ViewData["FinancialYears"] = _context.FinancialYear.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.StartDate.Year + " - " + a.EndDate.Year
                                            }).ToList();
            ViewData["RAMs"] = _userManager.Users.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.Id.ToString(),
                                                Text = a.FirstName + " " + a.LastName
                                            }).ToList();
            FinancialYear financialYear = await _context.FinancialYear.FirstOrDefaultAsync(f => f.Id == FinancialYearId);
            RAMDailyCollectionReports = await _context.RAMDailyCollectionReport
                .Include(d => d.RAM)
                .Include(d => d.RAMDailyCollections)
                .Where(d => d.RAMId == RAMId && d.SalesDate.Month == Month && d.ApprovalStatus == "Approved").ToListAsync();

            RAMDailyCollections = await _context.RAMDailyCollection
                    .Include(d => d.MainDistributor)
                    .Include(d => d.RAMDailyCollectionReport)
                    .Where(d => d.RAMDailyCollectionReport.RAMId == RAMId && d.RAMDailyCollectionReport.SalesDate.Month == Month && (d.RAMDailyCollectionReport.SalesDate.Year == financialYear.StartDate.Year || d.RAMDailyCollectionReport.SalesDate.Year == financialYear.EndDate.Year) && d.RAMDailyCollectionReport.ApprovalStatus == "Approved").ToListAsync();
            RAMCollectionTargets = await _context.RAMCollectionTarget
                .Include(s => s.FinancialYear)
                .Include(s => s.RAM)
                .Include(s => s.RAMCollectionTargetMappings)
                .Where(s => s.ApprovalStatus == "Approved").ToListAsync();

            RAMCollectionTargetMappings = await _context.RAMCollectionTargetMapping
                    .Include(t => t.MainDistributor)
                    .Include(t => t.RAMCollectionTarget)
                    .Where(d => d.RAMCollectionTarget.RAMId == RAMId && d.RAMCollectionTarget.Month == Month && d.RAMCollectionTarget.FinancialYearId == financialYear.Id && d.RAMCollectionTarget.ApprovalStatus == "Approved").ToListAsync();
            _toastNotification.Success("Report Ready!");
            return Page();
        }
    }
}

TwigaCRM/Pages/PerformanceReports/PerformanceReports.cshtml
@page
@model TwigaCRM.Pages.PerformanceReports.PerformanceReportsModel

@{
    ViewData["Title"] = "PerformanceReports";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<style>
    .select2-selection__rendered {
        line-height: 31px !important;
    }

    .select2-container .select2-selection--single {
        height: 35px !important;
    }

    .select2-selection__arrow {
        height: 34px !important;
    }
</style>
<div class="container-fluid">
    <div class="card card-outline card-primary">
        <div class="card-header text-center row">
            <p class="h2 col-md-12">Performance Report</p>
            @*<a asp-page="./DemoPrintOut" asp-route-id="@Model.Demo.Id" class="btn btn-success col-md-2">Generate Print Out</a>*@
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <p class="font-weight-bolder h3">Monthly Performance Report</p>
                </div>
                <div class="col-12">
                    <form class="form-row" method="post">
                        <div class="col-md-3 mx-2">
                            <label asp-for="Input.SalesPersonId">Sales Person</label>
                            <div class="row">
                                <select id="ddlSalesPersons" asp-for="Input.SalesPersonId" name="Input.SalesPersonId" asp-items="ViewBag.SalesPersons" class="form-control" style="width: 100%">
                                    <option value="">--  Select SalesPersons  --</option>
                                </select>
                            </div>
                            <span asp-validation-for="Input.SalesPersonId" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mx-2">
                            <label asp-for="Input.Month" class="control-label"></label>
                            <select asp-for="Input.Month" class="form-control">
                                <option value="">-- Select Month --</option>
                                <option value="1">JAN</option>
                                <option value="2">FEB</option>
                                <option value="3">MAR</option>
                                <option value="4">APR</option>
                                <option value="5">MAY</option>
                                <option value="6">JUN</option>
                                <option value="7">JUL</option>
                                <option value="8">AUG</option>
                                <option value="9">SEP</option>
                                <option value="10">OCT</option>
                                <option value="11">NOV</option>
                                <option value="12">DEC</option>
                            </select>
                            <span asp-validation-for="Input.Month" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mx-2">
                            <label asp-for="Input.FinancialYearId">Financial Year</label>
                            <div class="row">
                                <select id="ddlFinancialYears" asp-for="Input.FinancialYearId" name="Input.FinancialYearId" asp-items="ViewBag.FinancialYears" class="form-control" style="width: 100%">
                                    <option value="">--  Select FinancialYears  --</option>
                                </select>
                            </div>
                            <span asp-validation-for="Input.FinancialYearId" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mt-4">
                            <button type="submit" class="btn btn-primary mb-2">Generate Month Report</button>
                        </div>
                        <div class="col-md-2 mt-4">
                            <button type="submit" asp-page-handler="WeeklyPerformance" class="btn btn-primary mb-2">Generate Week Report</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    <script>
        $(document).ready(function () {
            $("#ddlFinancialYears").select2();
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#ddlSalesPersons").select2();
        });
    </script>
    <script type="text/javascript">
        $("body").on("change", "#ddlFinancialYears", function () {
            $("input[name=FinancialYearId]").val($(this).find("option:selected").text());
        });
    </script>
    <script type="text/javascript">
        $("body").on("change", "#ddlSalesPersons", function () {
            $("input[name=SalesPersonId]").val($(this).find("option:selected").text());
        });
    </script>

TwigaCRM/Pages/PerformanceReports/RAMCollectionPerformanceReports.cshtml
@page
@model TwigaCRM.Pages.PerformanceReports.RAMCollectionPerformanceReportsModel

@{
    ViewData["Title"] = "RAM Collection Performance Reports";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<style>
    .select2-selection__rendered {
        line-height: 31px !important;
    }

    .select2-container .select2-selection--single {
        height: 35px !important;
    }

    .select2-selection__arrow {
        height: 34px !important;
    }
</style>
<div class="container-fluid">
    <div class="card card-outline card-primary">
        <div class="card-header text-center row">
            <p class="h2 col-md-12">RAM Collection Performance Report</p>
            @*<a asp-page="./DemoPrintOut" asp-route-id="@Model.Demo.Id" class="btn btn-success col-md-2">Generate Print Out</a>*@
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <p class="font-weight-bolder h3">RAM Collection Performance Report</p>
                </div>
                <div class="col-12">
                    <form class="form-row" method="post">
                        <div class="col-md-3 mx-2">
                            <label asp-for="Input.RAMId">R.A.M</label>
                            <div class="row">
                                <select id="ddlRAMs" asp-for="Input.RAMId" name="Input.RAMId" asp-items="ViewBag.RAMs" class="form-control" style="width: 100%">
                                    <option value="">--  Select RAMs  --</option>
                                </select>
                            </div>
                            <span asp-validation-for="Input.RAMId" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mx-2">
                            <label asp-for="Input.Month" class="control-label"></label>
                            <select asp-for="Input.Month" class="form-control">
                                <option value="">-- Select Month --</option>
                                <option value="1">JAN</option>
                                <option value="2">FEB</option>
                                <option value="3">MAR</option>
                                <option value="4">APR</option>
                                <option value="5">MAY</option>
                                <option value="6">JUN</option>
                                <option value="7">JUL</option>
                                <option value="8">AUG</option>
                                <option value="9">SEP</option>
                                <option value="10">OCT</option>
                                <option value="11">NOV</option>
                                <option value="12">DEC</option>
                            </select>
                            <span asp-validation-for="Input.Month" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mx-2">
                            <label asp-for="Input.FinancialYearId">Financial Year</label>
                            <div class="row">
                                <select id="ddlFinancialYears" asp-for="Input.FinancialYearId" name="Input.FinancialYearId" asp-items="ViewBag.FinancialYears" class="form-control" style="width: 100%">
                                    <option value="">--  Select FinancialYears  --</option>
                                </select>
                            </div>
                            <span asp-validation-for="Input.FinancialYearId" class="text-danger"></span>
                        </div>
                        <div class="col-md-2 mt-4">
                            <button type="submit" class="btn btn-primary mb-2">Generate Month Report</button>
                        </div>
                        <div class="col-md-2 mt-4">
                            <button type="submit" asp-page-handler="WeeklyPerformance" class="btn btn-primary mb-2">Generate Week Report</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    <script>
        $(document).ready(function () {
            $("#ddlFinancialYears").select2();
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#ddlRAMs").select2();
        });
    </script>
    <script type="text/javascript">
        $("body").on("change", "#ddlFinancialYears", function () {
            $("input[name=FinancialYearId]").val($(this).find("option:selected").text());
        });
    </script>
    <script type="text/javascript">
        $("body").on("change", "#ddlRAMs", function () {
            $("input[name=RAMId]").val($(this).find("option:selected").text());
        });
    </script>